---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package on file server
    apt:
      name: samba
      state: latest
